/*
 * This file is generated by jOOQ.
 */
package org.igsq.igsqbot.entities.jooq;


import org.jooq.Sequence;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all sequences in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.mutes_muteid_seq</code>
     */
    public static final Sequence<Long> MUTES_MUTEID_SEQ = Internal.createSequence("mutes_muteid_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.reaction_roles_reactionroleid_seq</code>
     */
    public static final Sequence<Long> REACTION_ROLES_REACTIONROLEID_SEQ = Internal.createSequence("reaction_roles_reactionroleid_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.reminders_reminderid_seq</code>
     */
    public static final Sequence<Long> REMINDERS_REMINDERID_SEQ = Internal.createSequence("reminders_reminderid_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.reports_reportid_seq</code>
     */
    public static final Sequence<Long> REPORTS_REPORTID_SEQ = Internal.createSequence("reports_reportid_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.roles_id_seq</code>
     */
    public static final Sequence<Long> ROLES_ID_SEQ = Internal.createSequence("roles_id_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.votes_voteid_seq</code>
     */
    public static final Sequence<Long> VOTES_VOTEID_SEQ = Internal.createSequence("votes_voteid_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.warnings_warnid_seq</code>
     */
    public static final Sequence<Long> WARNINGS_WARNID_SEQ = Internal.createSequence("warnings_warnid_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);
}
