/*
 * This file is generated by jOOQ.
 */
package org.igsq.igsqbot.entities.jooq;


import org.jooq.generated.tables.Blacklists;
import org.jooq.generated.tables.Guilds;
import org.jooq.generated.tables.Levels;
import org.jooq.generated.tables.ReactionRoles;
import org.jooq.generated.tables.Reminders;
import org.jooq.generated.tables.Reports;
import org.jooq.generated.tables.Roles;
import org.jooq.generated.tables.Tempbans;
import org.jooq.generated.tables.Votes;
import org.jooq.generated.tables.Warnings;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.blacklists</code>.
     */
    public static final Blacklists BLACKLISTS = Blacklists.BLACKLISTS;

    /**
     * The table <code>public.guilds</code>.
     */
    public static final Guilds GUILDS = Guilds.GUILDS;

    /**
     * The table <code>public.levels</code>.
     */
    public static final Levels LEVELS = Levels.LEVELS;

    /**
     * The table <code>public.reaction_roles</code>.
     */
    public static final ReactionRoles REACTION_ROLES = ReactionRoles.REACTION_ROLES;

    /**
     * The table <code>public.reminders</code>.
     */
    public static final Reminders REMINDERS = Reminders.REMINDERS;

    /**
     * The table <code>public.reports</code>.
     */
    public static final Reports REPORTS = Reports.REPORTS;

    /**
     * The table <code>public.roles</code>.
     */
    public static final Roles ROLES = Roles.ROLES;

    /**
     * The table <code>public.tempbans</code>.
     */
    public static final Tempbans TEMPBANS = Tempbans.TEMPBANS;

    /**
     * The table <code>public.votes</code>.
     */
    public static final Votes VOTES = Votes.VOTES;

    /**
     * The table <code>public.warnings</code>.
     */
    public static final Warnings WARNINGS = Warnings.WARNINGS;
}
