/*
 * This file is generated by jOOQ.
 */
package org.igsq.igsqbot.entities.jooq;


import org.igsq.igsqbot.entities.jooq.tables.*;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables
{

    /**
     * The table <code>public.guilds</code>.
     */
    public static final Guilds GUILDS = Guilds.GUILDS;

    /**
     * The table <code>public.mutes</code>.
     */
    public static final Mutes MUTES = Mutes.MUTES;

    /**
     * The table <code>public.reaction_roles</code>.
     */
    public static final ReactionRoles REACTION_ROLES = ReactionRoles.REACTION_ROLES;

    /**
     * The table <code>public.reminders</code>.
     */
    public static final Reminders REMINDERS = Reminders.REMINDERS;

    /**
     * The table <code>public.reports</code>.
     */
    public static final Reports REPORTS = Reports.REPORTS;

    /**
     * The table <code>public.roles</code>.
     */
    public static final Roles ROLES = Roles.ROLES;

    /**
     * The table <code>public.votes</code>.
     */
    public static final Votes VOTES = Votes.VOTES;

    /**
     * The table <code>public.warnings</code>.
     */
    public static final Warnings WARNINGS = Warnings.WARNINGS;
}
