CREATE TABLE IF NOT EXISTS mutes
(
    id bigserial PRIMARY KEY NOT NULL,
    userid BIGINT NOT NULL UNIQUE,
    guildid BIGINT NOT NULL UNIQUE REFERENCES guilds(guildId) ON DELETE CASCADE,
    muteduntil TIMESTAMP NOT NULL
);