CREATE TABLE IF NOT EXISTS mutes
(
    id bigserial PRIMARY KEY NOT NULL,
    userId BIGINT NOT NULL UNIQUE,
    guildId BIGINT NOT NULL UNIQUE REFERENCES guilds(guildId) ON DELETE CASCADE,
    mutedUntil TIMESTAMP NOT NULL
);