CREATE TABLE IF NOT EXISTS reaction_roles
(
    id BIGSERIAL NOT NULL PRIMARY KEY,
    guildid BIGINT NOT NULL REFERENCES guilds(guildId) ON DELETE CASCADE,
    emoteid VARCHAR(25) NULL,
    roleid BIGINT NULL
);