CREATE TABLE IF NOT EXISTS reminders
(
    id BIGSERIAL NOT NULL PRIMARY KEY,
    guildid BIGINT NOT NULL REFERENCES guilds(guildId) ON DELETE CASCADE,
    userid BIGINT NOT NULL,
    remindertext TEXT NOT NULL
);