CREATE TABLE IF NOT EXISTS reminders
(
    id BIGSERIAL NOT NULL PRIMARY KEY,
    guildId BIGINT NOT NULL REFERENCES guilds(guildId) ON DELETE CASCADE,
    userId BIGINT NOT NULL,
    reminderText TEXT NOT NULL
);