CREATE TABLE IF NOT EXISTS roles
(
    id BIGSERIAL PRIMARY KEY NOT NULL,
    userId BIGINT NOT NULL UNIQUE,
    guildId BIGINT NOT NULL UNIQUE references guilds(guildId) ON DELETE CASCADE,
    roleId BIGINT NOT NULL
);