CREATE TABLE IF NOT EXISTS roles
(
    id BIGSERIAL PRIMARY KEY NOT NULL,
    userId BIGINT NOT NULL,
    guildId BIGINT NOT NULL REFERENCES guilds(guildId) ON DELETE CASCADE,
    roleId BIGINT NOT NULL
);