CREATE TABLE IF NOT EXISTS votes
(
    id BIGSERIAL NOT NULL PRIMARY KEY,
    voteId BIGINT NOT NULL,
    messageId BIGINT NOT NULL,
    option CHAR NOT NULL DEFAULT -1,
    timeStamp TIMESTAMP NOT NULL
);