CREATE TABLE IF NOT EXISTS votes
(
    id BIGSERIAL NOT NULL PRIMARY KEY,
    voteid BIGINT NOT NULL,
    messageid BIGINT NOT NULL,
    option CHAR NOT NULL DEFAULT -1,
    timestamp TIMESTAMP NOT NULL
);