/*
 * This file is generated by jOOQ.
 */
package org.igsq.igsqbot.entities.jooq.tables.records;


import org.igsq.igsqbot.entities.jooq.tables.Blacklists;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.generated.tables.Blacklists;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BlacklistsRecord extends UpdatableRecordImpl<BlacklistsRecord> implements Record3<Long, Long, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.blacklists.id</code>.
     */
    public BlacklistsRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.blacklists.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.blacklists.guild_id</code>.
     */
    public BlacklistsRecord setGuildId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.blacklists.guild_id</code>.
     */
    public Long getGuildId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.blacklists.phrase</code>.
     */
    public BlacklistsRecord setPhrase(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.blacklists.phrase</code>.
     */
    public String getPhrase() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, Long, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Long, Long, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Blacklists.BLACKLISTS.ID;
    }

    @Override
    public Field<Long> field2() {
        return Blacklists.BLACKLISTS.GUILD_ID;
    }

    @Override
    public Field<String> field3() {
        return Blacklists.BLACKLISTS.PHRASE;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getGuildId();
    }

    @Override
    public String component3() {
        return getPhrase();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getGuildId();
    }

    @Override
    public String value3() {
        return getPhrase();
    }

    @Override
    public BlacklistsRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public BlacklistsRecord value2(Long value) {
        setGuildId(value);
        return this;
    }

    @Override
    public BlacklistsRecord value3(String value) {
        setPhrase(value);
        return this;
    }

    @Override
    public BlacklistsRecord values(Long value1, Long value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BlacklistsRecord
     */
    public BlacklistsRecord() {
        super(Blacklists.BLACKLISTS);
    }

    /**
     * Create a detached, initialised BlacklistsRecord
     */
    public BlacklistsRecord(Long id, Long guildId, String phrase) {
        super(Blacklists.BLACKLISTS);

        setId(id);
        setGuildId(guildId);
        setPhrase(phrase);
    }
}
