/*
 * This file is generated by jOOQ.
 */
package org.igsq.igsqbot.entities.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.igsq.igsqbot.entities.jooq.tables.ReactionRoles;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReactionRolesRecord extends UpdatableRecordImpl<ReactionRolesRecord> implements Record5<Long, Long, Long, String, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.reaction_roles.id</code>.
     */
    public ReactionRolesRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.reaction_roles.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.reaction_roles.messageid</code>.
     */
    public ReactionRolesRecord setMessageid(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.reaction_roles.messageid</code>.
     */
    public Long getMessageid() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.reaction_roles.guildid</code>.
     */
    public ReactionRolesRecord setGuildid(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.reaction_roles.guildid</code>.
     */
    public Long getGuildid() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.reaction_roles.emoteid</code>.
     */
    public ReactionRolesRecord setEmoteid(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.reaction_roles.emoteid</code>.
     */
    public String getEmoteid() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.reaction_roles.roleid</code>.
     */
    public ReactionRolesRecord setRoleid(Long value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.reaction_roles.roleid</code>.
     */
    public Long getRoleid() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, Long, Long, String, Long> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, Long, Long, String, Long> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return ReactionRoles.REACTION_ROLES.ID;
    }

    @Override
    public Field<Long> field2() {
        return ReactionRoles.REACTION_ROLES.MESSAGEID;
    }

    @Override
    public Field<Long> field3() {
        return ReactionRoles.REACTION_ROLES.GUILDID;
    }

    @Override
    public Field<String> field4() {
        return ReactionRoles.REACTION_ROLES.EMOTEID;
    }

    @Override
    public Field<Long> field5() {
        return ReactionRoles.REACTION_ROLES.ROLEID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getMessageid();
    }

    @Override
    public Long component3() {
        return getGuildid();
    }

    @Override
    public String component4() {
        return getEmoteid();
    }

    @Override
    public Long component5() {
        return getRoleid();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getMessageid();
    }

    @Override
    public Long value3() {
        return getGuildid();
    }

    @Override
    public String value4() {
        return getEmoteid();
    }

    @Override
    public Long value5() {
        return getRoleid();
    }

    @Override
    public ReactionRolesRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public ReactionRolesRecord value2(Long value) {
        setMessageid(value);
        return this;
    }

    @Override
    public ReactionRolesRecord value3(Long value) {
        setGuildid(value);
        return this;
    }

    @Override
    public ReactionRolesRecord value4(String value) {
        setEmoteid(value);
        return this;
    }

    @Override
    public ReactionRolesRecord value5(Long value) {
        setRoleid(value);
        return this;
    }

    @Override
    public ReactionRolesRecord values(Long value1, Long value2, Long value3, String value4, Long value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReactionRolesRecord
     */
    public ReactionRolesRecord() {
        super(ReactionRoles.REACTION_ROLES);
    }

    /**
     * Create a detached, initialised ReactionRolesRecord
     */
    public ReactionRolesRecord(Long id, Long messageid, Long guildid, String emoteid, Long roleid) {
        super(ReactionRoles.REACTION_ROLES);

        setId(id);
        setMessageid(messageid);
        setGuildid(guildid);
        setEmoteid(emoteid);
        setRoleid(roleid);
    }
}
