/*
 * This file is generated by jOOQ.
 */
package org.igsq.igsqbot.entities.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Guilds implements Serializable
{

	private static final long serialVersionUID = 1L;

	private final Long guildid;
	private final Long logchannel;
	private final Long mutedrole;
	private final Long verifiedrole;
	private final Long reportchannel;
	private final Long votechannel;
	private final Long suggestionchannel;
	private final String prefix;

	public Guilds(Guilds value)
	{
		this.guildid = value.guildid;
		this.logchannel = value.logchannel;
		this.mutedrole = value.mutedrole;
		this.verifiedrole = value.verifiedrole;
		this.reportchannel = value.reportchannel;
		this.votechannel = value.votechannel;
		this.suggestionchannel = value.suggestionchannel;
		this.prefix = value.prefix;
	}

	public Guilds(
			Long guildid,
			Long logchannel,
			Long mutedrole,
			Long verifiedrole,
			Long reportchannel,
			Long votechannel,
			Long suggestionchannel,
			String prefix
	)
	{
		this.guildid = guildid;
		this.logchannel = logchannel;
		this.mutedrole = mutedrole;
		this.verifiedrole = verifiedrole;
		this.reportchannel = reportchannel;
		this.votechannel = votechannel;
		this.suggestionchannel = suggestionchannel;
		this.prefix = prefix;
	}

	/**
	 * Getter for <code>public.guilds.guildid</code>.
	 */
	public Long getGuildid()
	{
		return this.guildid;
	}

	/**
	 * Getter for <code>public.guilds.logchannel</code>.
	 */
	public Long getLogchannel()
	{
		return this.logchannel;
	}

	/**
	 * Getter for <code>public.guilds.mutedrole</code>.
	 */
	public Long getMutedrole()
	{
		return this.mutedrole;
	}

	/**
	 * Getter for <code>public.guilds.verifiedrole</code>.
	 */
	public Long getVerifiedrole()
	{
		return this.verifiedrole;
	}

	/**
	 * Getter for <code>public.guilds.reportchannel</code>.
	 */
	public Long getReportchannel()
	{
		return this.reportchannel;
	}

	/**
	 * Getter for <code>public.guilds.votechannel</code>.
	 */
	public Long getVotechannel()
	{
		return this.votechannel;
	}

	/**
	 * Getter for <code>public.guilds.suggestionchannel</code>.
	 */
	public Long getSuggestionchannel()
	{
		return this.suggestionchannel;
	}

	/**
	 * Getter for <code>public.guilds.prefix</code>.
	 */
	public String getPrefix()
	{
		return this.prefix;
	}

	@Override
	public String toString()
	{
		StringBuilder sb = new StringBuilder("Guilds (");

		sb.append(guildid);
		sb.append(", ").append(logchannel);
		sb.append(", ").append(mutedrole);
		sb.append(", ").append(verifiedrole);
		sb.append(", ").append(reportchannel);
		sb.append(", ").append(votechannel);
		sb.append(", ").append(suggestionchannel);
		sb.append(", ").append(prefix);

		sb.append(")");
		return sb.toString();
	}
}
