/*
 * This file is generated by jOOQ.
 */
package org.igsq.igsqbot.entities.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReactionRoles implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long   reactionroleid;
    private final Long   guildid;
    private final String emoteid;
    private final Long   roleid;

    public ReactionRoles(ReactionRoles value) {
        this.reactionroleid = value.reactionroleid;
        this.guildid = value.guildid;
        this.emoteid = value.emoteid;
        this.roleid = value.roleid;
    }

    public ReactionRoles(
        Long   reactionroleid,
        Long   guildid,
        String emoteid,
        Long   roleid
    ) {
        this.reactionroleid = reactionroleid;
        this.guildid = guildid;
        this.emoteid = emoteid;
        this.roleid = roleid;
    }

    /**
     * Getter for <code>public.reaction_roles.reactionroleid</code>.
     */
    public Long getReactionroleid() {
        return this.reactionroleid;
    }

    /**
     * Getter for <code>public.reaction_roles.guildid</code>.
     */
    public Long getGuildid() {
        return this.guildid;
    }

    /**
     * Getter for <code>public.reaction_roles.emoteid</code>.
     */
    public String getEmoteid() {
        return this.emoteid;
    }

    /**
     * Getter for <code>public.reaction_roles.roleid</code>.
     */
    public Long getRoleid() {
        return this.roleid;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ReactionRoles (");

        sb.append(reactionroleid);
        sb.append(", ").append(guildid);
        sb.append(", ").append(emoteid);
        sb.append(", ").append(roleid);

        sb.append(")");
        return sb.toString();
    }
}
