/*
 * This file is generated by jOOQ.
 */
package org.igsq.igsqbot.entities.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Reminders implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long   id;
    private final Long   guildid;
    private final Long   userid;
    private final String remindertext;

    public Reminders(Reminders value) {
        this.id = value.id;
        this.guildid = value.guildid;
        this.userid = value.userid;
        this.remindertext = value.remindertext;
    }

    public Reminders(
        Long   id,
        Long   guildid,
        Long   userid,
        String remindertext
    ) {
        this.id = id;
        this.guildid = guildid;
        this.userid = userid;
        this.remindertext = remindertext;
    }

    /**
     * Getter for <code>public.reminders.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.reminders.guildid</code>.
     */
    public Long getGuildid() {
        return this.guildid;
    }

    /**
     * Getter for <code>public.reminders.userid</code>.
     */
    public Long getUserid() {
        return this.userid;
    }

    /**
     * Getter for <code>public.reminders.remindertext</code>.
     */
    public String getRemindertext() {
        return this.remindertext;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Reminders (");

        sb.append(id);
        sb.append(", ").append(guildid);
        sb.append(", ").append(userid);
        sb.append(", ").append(remindertext);

        sb.append(")");
        return sb.toString();
    }
}
