/*
 * This file is generated by jOOQ.
 */
package org.igsq.igsqbot.entities.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Reports implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long          reportid;
    private final Long          messageid;
    private final Long          reportmessageid;
    private final Long          channelid;
    private final Long          guildid;
    private final Long          userid;
    private final LocalDateTime timestamp;
    private final String        reporttext;

    public Reports(Reports value) {
        this.reportid = value.reportid;
        this.messageid = value.messageid;
        this.reportmessageid = value.reportmessageid;
        this.channelid = value.channelid;
        this.guildid = value.guildid;
        this.userid = value.userid;
        this.timestamp = value.timestamp;
        this.reporttext = value.reporttext;
    }

    public Reports(
        Long          reportid,
        Long          messageid,
        Long          reportmessageid,
        Long          channelid,
        Long          guildid,
        Long          userid,
        LocalDateTime timestamp,
        String        reporttext
    ) {
        this.reportid = reportid;
        this.messageid = messageid;
        this.reportmessageid = reportmessageid;
        this.channelid = channelid;
        this.guildid = guildid;
        this.userid = userid;
        this.timestamp = timestamp;
        this.reporttext = reporttext;
    }

    /**
     * Getter for <code>public.reports.reportid</code>.
     */
    public Long getReportid() {
        return this.reportid;
    }

    /**
     * Getter for <code>public.reports.messageid</code>.
     */
    public Long getMessageid() {
        return this.messageid;
    }

    /**
     * Getter for <code>public.reports.reportmessageid</code>.
     */
    public Long getReportmessageid() {
        return this.reportmessageid;
    }

    /**
     * Getter for <code>public.reports.channelid</code>.
     */
    public Long getChannelid() {
        return this.channelid;
    }

    /**
     * Getter for <code>public.reports.guildid</code>.
     */
    public Long getGuildid() {
        return this.guildid;
    }

    /**
     * Getter for <code>public.reports.userid</code>.
     */
    public Long getUserid() {
        return this.userid;
    }

    /**
     * Getter for <code>public.reports.timestamp</code>.
     */
    public LocalDateTime getTimestamp() {
        return this.timestamp;
    }

    /**
     * Getter for <code>public.reports.reporttext</code>.
     */
    public String getReporttext() {
        return this.reporttext;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Reports (");

        sb.append(reportid);
        sb.append(", ").append(messageid);
        sb.append(", ").append(reportmessageid);
        sb.append(", ").append(channelid);
        sb.append(", ").append(guildid);
        sb.append(", ").append(userid);
        sb.append(", ").append(timestamp);
        sb.append(", ").append(reporttext);

        sb.append(")");
        return sb.toString();
    }
}
