/*
 * This file is generated by jOOQ.
 */
package org.igsq.igsqbot.entities.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Users implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long id;
    private final Long userid;
    private final Long guildid;

    public Users(Users value) {
        this.id = value.id;
        this.userid = value.userid;
        this.guildid = value.guildid;
    }

    public Users(
        Long id,
        Long userid,
        Long guildid
    ) {
        this.id = id;
        this.userid = userid;
        this.guildid = guildid;
    }

    /**
     * Getter for <code>public.users.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.users.userid</code>.
     */
    public Long getUserid() {
        return this.userid;
    }

    /**
     * Getter for <code>public.users.guildid</code>.
     */
    public Long getGuildid() {
        return this.guildid;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Users (");

        sb.append(id);
        sb.append(", ").append(userid);
        sb.append(", ").append(guildid);

        sb.append(")");
        return sb.toString();
    }
}
