/*
 * This file is generated by jOOQ.
 */
package org.igsq.igsqbot.entities.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Votes implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long          voteid;
    private final Long          guildid;
    private final LocalDateTime timestamp;
    private final String        topic;
    private final String        optionone;
    private final String        optiontwo;
    private final Integer       votecountone;
    private final Integer       votecounttwo;

    public Votes(Votes value) {
        this.voteid = value.voteid;
        this.guildid = value.guildid;
        this.timestamp = value.timestamp;
        this.topic = value.topic;
        this.optionone = value.optionone;
        this.optiontwo = value.optiontwo;
        this.votecountone = value.votecountone;
        this.votecounttwo = value.votecounttwo;
    }

    public Votes(
        Long          voteid,
        Long          guildid,
        LocalDateTime timestamp,
        String        topic,
        String        optionone,
        String        optiontwo,
        Integer       votecountone,
        Integer       votecounttwo
    ) {
        this.voteid = voteid;
        this.guildid = guildid;
        this.timestamp = timestamp;
        this.topic = topic;
        this.optionone = optionone;
        this.optiontwo = optiontwo;
        this.votecountone = votecountone;
        this.votecounttwo = votecounttwo;
    }

    /**
     * Getter for <code>public.votes.voteid</code>.
     */
    public Long getVoteid() {
        return this.voteid;
    }

    /**
     * Getter for <code>public.votes.guildid</code>.
     */
    public Long getGuildid() {
        return this.guildid;
    }

    /**
     * Getter for <code>public.votes.timestamp</code>.
     */
    public LocalDateTime getTimestamp() {
        return this.timestamp;
    }

    /**
     * Getter for <code>public.votes.topic</code>.
     */
    public String getTopic() {
        return this.topic;
    }

    /**
     * Getter for <code>public.votes.optionone</code>.
     */
    public String getOptionone() {
        return this.optionone;
    }

    /**
     * Getter for <code>public.votes.optiontwo</code>.
     */
    public String getOptiontwo() {
        return this.optiontwo;
    }

    /**
     * Getter for <code>public.votes.votecountone</code>.
     */
    public Integer getVotecountone() {
        return this.votecountone;
    }

    /**
     * Getter for <code>public.votes.votecounttwo</code>.
     */
    public Integer getVotecounttwo() {
        return this.votecounttwo;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Votes (");

        sb.append(voteid);
        sb.append(", ").append(guildid);
        sb.append(", ").append(timestamp);
        sb.append(", ").append(topic);
        sb.append(", ").append(optionone);
        sb.append(", ").append(optiontwo);
        sb.append(", ").append(votecountone);
        sb.append(", ").append(votecounttwo);

        sb.append(")");
        return sb.toString();
    }
}
