/*
 * This file is generated by jOOQ.
 */
package org.igsq.igsqbot.entities.jooq.tables.pojos;


import java.io.Serializable;
import java.util.Arrays;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Votes implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long      id;
    private final Long      voteid;
    private final Long[]    allowedroles;
    private final Integer[] receivedvotes;
    private final Integer   maxvotes;

    public Votes(Votes value) {
        this.id = value.id;
        this.voteid = value.voteid;
        this.allowedroles = value.allowedroles;
        this.receivedvotes = value.receivedvotes;
        this.maxvotes = value.maxvotes;
    }

    public Votes(
        Long      id,
        Long      voteid,
        Long[]    allowedroles,
        Integer[] receivedvotes,
        Integer   maxvotes
    ) {
        this.id = id;
        this.voteid = voteid;
        this.allowedroles = allowedroles;
        this.receivedvotes = receivedvotes;
        this.maxvotes = maxvotes;
    }

    /**
     * Getter for <code>public.votes.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.votes.voteid</code>.
     */
    public Long getVoteid() {
        return this.voteid;
    }

    /**
     * Getter for <code>public.votes.allowedroles</code>.
     */
    public Long[] getAllowedroles() {
        return this.allowedroles;
    }

    /**
     * Getter for <code>public.votes.receivedvotes</code>.
     */
    public Integer[] getReceivedvotes() {
        return this.receivedvotes;
    }

    /**
     * Getter for <code>public.votes.maxvotes</code>.
     */
    public Integer getMaxvotes() {
        return this.maxvotes;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Votes (");

        sb.append(id);
        sb.append(", ").append(voteid);
        sb.append(", ").append(Arrays.toString(allowedroles));
        sb.append(", ").append(Arrays.toString(receivedvotes));
        sb.append(", ").append(maxvotes);

        sb.append(")");
        return sb.toString();
    }
}
