/*
 * This file is generated by jOOQ.
 */
package org.igsq.igsqbot.entities.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Warnings implements Serializable
{

	private static final long serialVersionUID = 1L;

	private final Long warnid;
	private final Long guildid;
	private final Long userid;
	private final LocalDateTime timestamp;
	private final String warntext;

	public Warnings(Warnings value)
	{
		this.warnid = value.warnid;
		this.guildid = value.guildid;
		this.userid = value.userid;
		this.timestamp = value.timestamp;
		this.warntext = value.warntext;
	}

	public Warnings(
			Long warnid,
			Long guildid,
			Long userid,
			LocalDateTime timestamp,
			String warntext
	)
	{
		this.warnid = warnid;
		this.guildid = guildid;
		this.userid = userid;
		this.timestamp = timestamp;
		this.warntext = warntext;
	}

	/**
	 * Getter for <code>public.warnings.warnid</code>.
	 */
	public Long getWarnid()
	{
		return this.warnid;
	}

	/**
	 * Getter for <code>public.warnings.guildid</code>.
	 */
	public Long getGuildid()
	{
		return this.guildid;
	}

	/**
	 * Getter for <code>public.warnings.userid</code>.
	 */
	public Long getUserid()
	{
		return this.userid;
	}

	/**
	 * Getter for <code>public.warnings.timestamp</code>.
	 */
	public LocalDateTime getTimestamp()
	{
		return this.timestamp;
	}

	/**
	 * Getter for <code>public.warnings.warntext</code>.
	 */
	public String getWarntext()
	{
		return this.warntext;
	}

	@Override
	public String toString()
	{
		StringBuilder sb = new StringBuilder("Warnings (");

		sb.append(warnid);
		sb.append(", ").append(guildid);
		sb.append(", ").append(userid);
		sb.append(", ").append(timestamp);
		sb.append(", ").append(warntext);

		sb.append(")");
		return sb.toString();
	}
}
